# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cef3b09de53982ecdab6326063db1b1f0496f2c90d76bc6bf6212027c03d6555624f990712e612c90b4ab4afaf71e5776a919646accbdb5c4bd15aae92339232

test:
  secret_key_base: 1ff4f1397cbfd9e78f7d0d537999e0080c3e1d4c5d06dcc9a9030ceed33d60fb11ecc916a79df3d59491f1bec9e4c6fd5d27f2b08752a2f3bdc5a2180b2950ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
